version: "3.9"

volumes:
    pgdata:

services:
    app:
        build: .
        container_name: app
        command: make migrate run h="0.0.0.0"
        env_file:
            - .env
        environment:
            DB_HOST: db
            PHP_INI_SCAN_DIR: ./
        ports:
            - "1337:8000"
        depends_on:
            - db

    db:
        image: postgres:14-alpine
        container_name: postgres
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data

